---
name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: >
          # Remove existing directory

          rm -rf gitops


          # ✅ Clone using token in URL — guaranteed to work

          git clone https://oauth2:${GIT_TOKEN}@github.com/babsontimie/grade-api-gitops.git gitops

          cd gitops


          # Optional: secure future Git pushes

          git config --global credential.helper '!f() { echo "username=oauth2"; echo "password=${GIT_TOKEN}"; }; f'

          cat deployment.yaml
          # Update image in deployment.yaml

          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: ghcr.io/${REPO}:.*|image: ghcr.io/${REPO}:${SHA}|g" deployment.yaml
          else
            sed -i "s|image: ghcr.io/${REPO}:.*|image: ghcr.io/${REPO}:${SHA}|g" deployment.yaml
          fi
          cat deployment.yaml

          # Commit and push changes

          git config --global user.name "GitHub Actions"

          git config --global user.email "actions@github.com"

          git add deployment.yaml

          git commit -m "Update image to ${SHA}" || echo "No changes to commit"

          git push origin main
