name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: babsontimie/kubernetes-api-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update deployment manifest and push changes
        working-directory: gitops
        run: |
          # Update image tag in deployment.yaml and argocd-application.yaml
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          sed -i "s|repoURL: ghcr.io/${{ github.repository }}:.*|repoURL: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" argocd-application.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f argocd-application.yaml
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Commit and push changes
          git add deployment.yaml argocd-application.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push https://oauth2:${{ secrets.GITOPS_PAT }}@github.com/babsontimie/kubernetes-api-gitops.git main
