name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          # git clone https://oauth2:${GIT_TOKEN}@github.com/babsontimie/grade-api-gitops.git gitops
          # cd gitops
          git clone https://babsontimie:${{ secrets.GH_PAT }}@github.com/babsontimie/grade-api-gitops.git
          cd gitops
          cat deployment.yaml
          git config --global credential.helper '!f() { echo "username=oauth2"; echo "password=${GIT_TOKEN}"; }; f'

          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: ghcr.io/${REPO}:.*|image: ghcr.io/${REPO}:${SHA}|g" deployment.yaml
          else
            sed -i "s|image: ghcr.io/${REPO}:.*|image: ghcr.io/${REPO}:${SHA}|g" deployment.yaml
          fi
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          #git push -f https://${GIT_TOKEN}@github.com/babsontimie/grade-api-gitops.git main
          git push origin main
